(deftheme BellePintosGrande
  "Created 2022-10-04.")

(custom-theme-set-faces
 'BellePintosGrande
 '(default ((t (:family "Ac437 Verite 8x16" :foundry "V.R." :width normal :height 128 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#F8F8F2" :background "#211e38" :stipple nil :inherit nil))))
 '(cursor ((t (:weight normal :underline nil :inverse-video t :foreground "#180e0f" :background "#bbf"))))
 '(fixed-pitch ((t (:family "Monospace" :weight normal :underline nil))))
 '(variable-pitch ((t (:family "Sans Serif" :weight normal :underline nil))))
 '(escape-glyph ((t (:weight normal :underline nil :foreground "#75715E"))))
 '(homoglyph ((t (:foreground "#8ABEB7" :underline nil :weight normal))))
 '(minibuffer-prompt ((t (:weight normal :underline nil :foreground "#99CCFF"))))
 '(highlight ((t (:weight normal :underline nil :background "#3e386a"))))
 '(region ((t (:weight normal :underline nil :extend t :background "#49483E" :inherit (highlight)))))
 '(shadow ((t (:weight normal :underline nil :foreground "#85818E"))))
 '(secondary-selection ((t (:inherit region :background "#A25C7B" :underline nil :weight normal))))
 '(trailing-whitespace ((t (:background "#d97f7f" :underline nil :weight normal))))
 '(font-lock-builtin-face ((t (:foreground "#D97F7F" :underline nil :weight normal))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :underline nil :foreground "#85856E"))))
 '(font-lock-comment-face ((t (:weight normal :underline nil :foreground "#85856E"))))
 '(font-lock-constant-face ((t (:foreground "#49838C" :underline nil :weight normal))))
 '(font-lock-doc-face ((t (:weight normal :underline nil :foreground "#E6DB74"))))
 '(font-lock-doc-markup-face ((t (:weight normal :underline nil :inherit font-lock-constant-face))))
 '(font-lock-function-name-face ((t (:foreground "#969F5A" :underline nil :weight normal))))
 '(font-lock-keyword-face ((t (:foreground "#D97F7F" :underline nil :weight normal))))
 '(font-lock-negation-char-face ((t (:weight normal :underline nil :foreground "#E6DB74"))))
 '(font-lock-preprocessor-face ((t (:foreground "#D97F7F" :underline nil :weight normal))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#49838C" :underline nil :weight normal))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :underline nil :foreground "#E6DB74"))))
 '(font-lock-string-face ((t (:weight normal :underline nil :foreground "#E6DB74"))))
 '(font-lock-type-face ((t (:foreground "#a0b4f9" :underline nil :slant normal :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "#DE8961" :underline nil :weight normal))))
 '(font-lock-warning-face ((t (:foreground "#DE8961" :underline nil :slant italic :weight normal))))
 '(button ((t (:weight normal :underline nil))))
 '(link ((t (:foreground "#a0b4f9" :underline nil :weight normal))))
 '(link-visited ((t (:weight normal :underline nil :foreground "#b294bb"))))
 '(fringe ((t (:weight normal :underline nil :foreground "#F8F8F2" :background "#211e38"))))
 '(header-line ((t (:weight normal :underline nil :box (:line-width (1 . 1) :color "#64645E" :style unspecified) :foreground "#F8F8F0" :background "#211e38"))))
 '(tooltip ((t (:weight normal :underline nil :foreground "#f8f8f3" :background "#3e386a" :inherit (default)))))
 '(mode-line ((t (:weight normal :underline nil :box (:line-width (1 . 1) :color "#52498c" :style unspecified) :foreground "#F8F8F0" :background "#52498C"))))
 '(mode-line-buffer-id ((t (:foreground "#F0C674" :underline nil :weight normal))))
 '(mode-line-emphasis ((t (:weight normal :underline nil))))
 '(mode-line-highlight ((t (:weight normal :underline nil :box (:line-width (2 . 2) :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:weight normal :underline nil :box (:line-width (1 . 1) :color "#3e386a" :style unspecified) :foreground "#f8f8f8" :background "#3e386a"))))
 '(isearch ((t (:inherit region :background "#F0C674" :foreground "#262626" :underline nil :weight normal))))
 '(isearch-fail ((t (:background "#D97F7F" :foreground "#262626" :underline nil :weight normal))))
 '(lazy-highlight ((t (:weight normal :underline nil :background "#3E3D31" :inherit (highlight)))))
 '(match ((t (:background "#F0C674" :foreground "#262626" :underline nil :weight normal))))
 '(next-error ((t (:weight normal :underline nil :inherit (region)))))
 '(query-replace ((t (:weight normal :underline nil :inherit isearch)))))

(provide-theme 'BellePintosGrande)
