(deftheme Macish
  "Created 2022-10-23.")

(custom-theme-set-faces
 'Macish
 '(default ((t (:family "Ac437 Verite 8x16" :foundry "V.R." :width normal :height 128 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#1b1b1b" :background "#efe8ef" :stipple nil :inherit nil))))
 '(cursor ((t (:weight normal :underline nil :inverse-video t :foreground "#1b1b1b" :background "#8F91B7"))))
 '(fixed-pitch ((t (:family "Monospace" :weight normal :underline nil))))
 '(variable-pitch ((t (:family "Sans Serif" :weight normal :underline nil))))
 '(escape-glyph ((t (:weight normal :underline nil :foreground "#75715E"))))
 '(homoglyph ((t (:weight normal :underline nil :foreground "#87adab"))))
 '(minibuffer-prompt ((t (:weight normal :underline nil :foreground "#87ADAB"))))
 '(highlight ((t (:background "seashell" :underline nil :weight normal))))
 '(region ((t (:weight normal :underline nil :extend t :background "#AFAFAF" :inherit (highlight)))))
 '(shadow ((t (:foreground "#AFAFAF" :underline nil :weight normal))))
 '(secondary-selection ((t (:weight normal :underline nil :background "#B48989" :inherit (region)))))
 '(trailing-whitespace ((t (:weight normal :underline nil :background "#B48989"))))
 '(font-lock-builtin-face ((t (:weight normal :underline nil :foreground "#B48989"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :underline nil :foreground "#afafaf"))))
 '(font-lock-comment-face ((t (:weight normal :underline nil :foreground "#6a6a6a"))))
 '(font-lock-constant-face ((t (:weight normal :underline nil :foreground "#87ADAB"))))
 '(font-lock-doc-face ((t (:weight normal :underline nil :foreground "#947C65"))))
 '(font-lock-doc-markup-face ((t (:weight normal :underline nil :inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:weight normal :underline nil :foreground "#969F5A"))))
 '(font-lock-keyword-face ((t (:weight normal :underline nil :foreground "#B48989"))))
 '(font-lock-negation-char-face ((t (:weight normal :underline nil :foreground "#947c65"))))
 '(font-lock-preprocessor-face ((t (:weight normal :underline nil :foreground "#B48989"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :underline nil :foreground "#87ADAB"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :underline nil :foreground "#947C65"))))
 '(font-lock-string-face ((t (:weight normal :underline nil :foreground "#947C65"))))
 '(font-lock-type-face ((t (:weight normal :slant normal :underline nil :foreground "#a0b4f9"))))
 '(font-lock-variable-name-face ((t (:weight normal :underline nil :foreground "#947C65"))))
 '(font-lock-warning-face ((t (:weight normal :slant italic :underline nil :foreground "#947C65"))))
 '(button ((t (:weight normal :underline nil))))
 '(link ((t (:weight normal :underline nil :foreground "#a0b4f9"))))
 '(link-visited ((t (:weight normal :underline nil :foreground "#A683A4"))))
 '(fringe ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#efe8ef"))))
 '(header-line ((t (:weight normal :underline nil :box (:line-width (1 . 1) :color "#1b1b1b" :style unspecified) :foreground "#1b1b1b" :background "#efe8ef"))))
 '(tooltip ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#efe8ef" :inherit default))))
 '(mode-line ((t (:background "#efe8ef" :foreground "#1b1b1b" :box (:line-width (1 . 1) :color "#efe8ef" :style unspecified) :underline nil :weight normal))))
 '(mode-line-buffer-id ((t (:weight normal :underline nil :foreground "#1b1b1b"))))
 '(mode-line-emphasis ((t (:background "#efe8ef" :foreground "#1b1b1b" :underline nil :weight normal))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "#b48989" :style released-button) :underline nil :weight normal))))
 '(mode-line-inactive ((t (:background "efe8ef" :foreground "#1b1b1b" :box (:line-width (1 . 1) :color "#efe9ef" :style unspecified) :underline nil :weight normal))))
 '(isearch ((t (:weight normal :underline nil :foreground "#262626" :background "#F0C674" :inherit (region)))))
 '(isearch-fail ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#B48989"))))
 '(lazy-highlight ((t (:weight normal :underline nil :background "#efe8ef" :inherit (highlight)))))
 '(match ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#947C65"))))
 '(next-error ((t (:weight normal :underline nil :inherit (region)))))
 '(query-replace ((t (:weight normal :underline nil :inherit (isearch))))))

(provide-theme 'Macish)
