(deftheme Macish
  "Created 2022-12-13.")

(custom-theme-set-faces
 'Macish
 '(default ((t (:family "Go Mono" :foundry "    " :width normal :height 103 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#1b1b1b" :background "#efe8ef" :stipple nil :inherit nil))))
 '(cursor ((t (:weight normal :underline nil :inverse-video t :foreground "#1b1b1b" :background "#8F91B7"))))
 '(fixed-pitch ((t (:family "Monospace" :weight normal :underline nil))))
 '(variable-pitch ((t (:family "Sans Serif" :weight normal :underline nil))))
 '(escape-glyph ((t (:weight normal :underline nil :foreground "#75715E"))))
 '(homoglyph ((t (:weight normal :underline nil :foreground "#61799C"))))
 '(minibuffer-prompt ((t (:weight normal :underline nil :foreground "#61799C"))))
 '(highlight ((t (:weight normal :underline nil :background "seashell"))))
 '(region ((t (:weight normal :underline nil :extend t :background "#E1DAE1" :inherit (highlight)))))
 '(shadow ((t (:weight normal :underline nil :foreground "#AFAFAF"))))
 '(secondary-selection ((t (:weight normal :underline nil :background "#9C5C5C" :inherit (region)))))
 '(trailing-whitespace ((t (:weight normal :underline nil :background "#C48E8E"))))
 '(font-lock-builtin-face ((t (:weight normal :underline nil :foreground "#C48E8E"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :underline nil :foreground "#6a6a6a"))))
 '(font-lock-comment-face ((t (:weight normal :underline nil :foreground "#6a6a6a"))))
 '(font-lock-constant-face ((t (:foreground "#5E9696" :underline nil :weight normal))))
 '(font-lock-doc-face ((t (:weight normal :underline nil :foreground "#947C65"))))
 '(font-lock-doc-markup-face ((t (:weight normal :underline nil :inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#65925C" :underline nil :weight normal))))
 '(font-lock-keyword-face ((t (:foreground "#9C5C5C" :underline nil :weight normal))))
 '(font-lock-negation-char-face ((t (:weight normal :underline nil :foreground "#947c65"))))
 '(font-lock-preprocessor-face ((t (:foreground "#9C5C5C" :underline nil :weight normal))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#5E9696" :underline nil :weight normal))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :underline nil :foreground "#947C65"))))
 '(font-lock-string-face ((t (:weight normal :underline nil :foreground "#947C65"))))
 '(font-lock-type-face ((t (:foreground "#61799C" :underline nil :slant normal :weight normal))))
 '(font-lock-variable-name-face ((t (:weight normal :underline nil :foreground "#947C65"))))
 '(font-lock-warning-face ((t (:weight normal :slant italic :underline nil :foreground "#947C65"))))
 '(button ((t (:weight normal :underline nil))))
 '(link ((t (:foreground "#61799C" :underline nil :weight normal))))
 '(link-visited ((t (:weight normal :underline nil :foreground "#A683A4"))))
 '(fringe ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#efe8ef"))))
 '(header-line ((t (:weight normal :underline nil :box (:line-width (1 . 1) :color "#1b1b1b" :style unspecified) :foreground "#1b1b1b" :background "#efe8ef"))))
 '(tooltip ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#efe8ef" :inherit (default)))))
 '(mode-line ((t (:weight normal :underline nil :box (:line-width (1 . 1) :color "#efe8ef" :style unspecified) :foreground "#1b1b1b" :background "#efe8ef"))))
 '(mode-line-buffer-id ((t (:weight normal :underline nil :foreground "#1b1b1b"))))
 '(mode-line-emphasis ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#efe8ef"))))
 '(mode-line-highlight ((t (:weight normal :underline nil :box (:line-width (2 . 2) :color "#C97272" :style released-button)))))
 '(mode-line-inactive ((t (:weight normal :underline nil :box (:line-width (1 . 1) :color "#efe9ef" :style unspecified) :foreground "#1b1b1b" :background "#efe8ef"))))
 '(isearch ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#A19E5E" :inherit (region)))))
 '(isearch-fail ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#9C5C5C"))))
 '(lazy-highlight ((t (:weight normal :underline nil :background "#efe8ef" :inherit (highlight)))))
 '(match ((t (:weight normal :underline nil :foreground "#1b1b1b" :background "#947C65"))))
 '(next-error ((t (:weight normal :underline nil :inherit (region)))))
 '(query-replace ((t (:weight normal :underline nil :inherit (isearch))))))

(provide-theme 'Macish)
